# Generated by Django 5.2.3 on 2025-06-25 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WitnessAlignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alignment", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WitnessType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="transcript",
            name="file",
            field=models.FileField(null=True, upload_to="transcripts"),
        ),
        migrations.AddField(
            model_name="witness",
            name="file",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.transcript",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="witness",
            name="alignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.witnessalignment",
            ),
        ),
        migrations.AlterField(
            model_name="witness",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.witnesstype"
            ),
        ),
    ]
