# Generated by Django 5.2.3 on 2025-07-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_witnessalignment_witnesstype_transcript_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.TextField()),
                ("index", models.FloatField()),
                ("cite", models.CharField(max_length=50)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.transcript",
                    ),
                ),
                (
                    "testimony",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.testimony",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
