# Generated by Django 5.2.3 on 2025-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="msal_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
