# Generated by Django 5.2.3 on 2025-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranscriptEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(blank=True, null=True)),
                ("answer", models.TextField(blank=True, null=True)),
                ("cite", models.TextField(blank=True, null=True)),
                ("filename", models.CharField(max_length=255)),
            ],
        ),
    ]
