# Generated by Django 5.2.3 on 2025-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_witnessentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilenameEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
            ],
        ),
    ]
